### ISSUE TITLE
heroku ps:forward TypeError normalizeConnectArgs is not a function

### ISSUE THREAD

**Issue by cast** [heroku/heroku-cli-exec#4]
heroku ps:forward is showing the following error on console when trying to remotely debug using the locally exposed port:

```
/Users/user/.local/share/heroku/plugins/node_modules/socksv5/lib/client.js:225
  var args = normalizeConnectArgs(arguments),
             ^

TypeError: normalizeConnectArgs is not a function
    at Object.exports.connect.exports.createConnection (/Users/user/.local/share/heroku/plugins/node_modules/socksv5/lib/client.js:225:14)
    at Server.<anonymous> (/Users/user/.local/share/heroku/plugins/node_modules/heroku-cli-exec/commands/port.js:39:15)
    at emitOne (events.js:96:13)
    at Server.emit (events.js:191:7)
    at TCP.onconnection (net.js:1473:8)

```
heroku ps:exec --status output:
``` 
=== app Heroku Exec status
Dyno   Proxy Status  Dyno Status
─────  ────────────  ───────────
web.1  running       up
```

#### Installed versions:
Heroku cli version: heroku-cli/5.8.6-061a13c (darwin-amd64) go1.7.5
heroku-cli-exec version: heroku-cli-exec 1.11.0

**Comment by ransombriggs** [comment]
@cast I shipped a new release on friday which should resolve this issue, could you `heroku update` and try again?
